#!/bin/bash

sleep=5
if ! [ -z $1 ] ; then 
	sleep=$1
fi

export sleep=$sleep
watch -t -n $sleep '

  echo "$(date) (sleep=$sleep)\n"

  for f in $(fail2ban-client status | grep Jail | cut -d ":" -f2 | xargs | tr -d ",") ; do 
    fail2ban-client status $f
  done
'

