version: "3"
services:
  app:
    container_name: nextCloud-app
    image: nextcloud:latest
    restart: unless-stopped
    
    # ports:
    #   - 8080:80
    
    volumes:
      - ./nextcloud_var_www_html:/var/www/html:rw 
    
    networks:
      nextCloud:
        external: true
        ipv4_address: 172.17.0.2

    environment:
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=2048M